version: 2

registries:
  maven-artifactory:
    type: maven-repository
    url: https://artifactory.sdlc.ctl.gcp.db.com/artifactory/mvn-public-local
    username: octocat
    password: ${{secrets.MY_ARTIFACTORY_PASSWORD}}
    #replaces-base: true

updates:
  - package-ecosystem: "maven"
    directory: "/maven-demo/"
    schedule:
      interval: "daily"
    target-branch: "target"
    labels:
      - "bug"
    registries:
      - maven-artifactory
      
      
  - package-ecosystem: "npm"
    directory: "/maven-demo/"
    schedule:
      interval: "daily"
    labels:
      - "invalid"

      

