name: Generate Dependabot Config

on:
  workflow_dispatch:

jobs:
  generate-dependabot-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Detect Package Manager
        id: detect-pm
        uses: skarab42/detect-package-manager@v1

      #- name: Generate Dependabot Config
       # id: generate-dependabot-config
        #uses: dependabot/generate-dependabot-glob@v1

      - name: Generate Dependabot Config
        id: generate-dependabot-config
        uses: dependabot/generate-dependabot-glob@v1
        with:
          package-ecosystem: ${{ steps.detect-pm.outputs.name }}
          directory: ${{ steps.detect-pm.outputs.directory }}


      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Add dependabot.yml file
          branch: add-dependabot-config
          title: Add dependabot.yml file
          body: |
            This pull request adds a dependabot.yml file generated by the [Generate Dependabot Glob] action.
            The file specifies the dependencies to be updated by Dependabot.
            The package manager detected is ${{ steps.detect-pm.outputs.name }} with version ${{ steps.detect-pm.outputs.version }}.
          path: .github/dependabot.yml
          reviewers: your-reviewers # optional
          labels: dependabot # optional
